base:
  log_level: INFO
  seed: 42

data:
  openml_settings:
    min_number_of_classes: 1
    max_number_of_classes: 15
    min_number_of_instances: 50
    max_number_of_instances: 900
    max_number_of_features: 60
    cols_to_load: [ "did", "name", "NumberOfInstances", "NumberOfFeatures", "NumberOfClasses", "version" ]
  filepaths:
    raw_openml_data_file: data/raw/openml_df.csv
    processed_data_file: data/processed/meta_df.csv
    figure_folder: reports/figures/

features_calcers:
  stats_features:
    percentages_step: 0.05
  mapper_features:
    num_pca_components: 2
    random_state: 2022
    cubical_cover_intervals: 10
    overlap_frac: 0.3
  tda_features:
    num_relevant_holes_theta: 0.55
  meta_features:
    clustering_algos:
      - KMeans
      - AgglomerativeClustering
      - SpectralClustering
    random_state: 2022

train:
  cv: 4
  test_size: 0.45
  grid_search_verbose: 1
  grid_search_scoring:
    F1_micro: f1_micro
    F1_macro: f1_macro
    AUC: roc_auc_ovr_weighted
  rf: # sklearn.ensemble.RandomForestClassifier
    param_grid:
      random_state: 2022
      n_estimators: [50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150, 160]
      max_depth: [ 5, 6, 7, 8, 9, 10, 11 ]
      min_samples_split: [ 2, 3, 4, 5, 6]
      min_samples_leaf: [ 1, 2, 3, 4, 5 ]
  model_path: models/
  f_importances:
    mdi:
      plot_file_name: mdi_f_imp_result.png
    permutation:
      n_repeats: 10
      plot_file_name: permutation_f_imp_result.png





